# Generated by Django 5.1.7 on 2025-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_remove_todo_modified_at_todo_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('cat', '고양이'), ('dog', '개')], default='free', max_length=20, verbose_name='카테고리'),
        ),
    ]
